potato<-read.csv('/Users/suedy/Desktop/potato_m.csv')
summary(potato)
library(ggplot2)
install.packages("lme4")
library(lme4)
res1 = lmer(Price ~ Country+Shape_of_tuber+Colour_of_skin+Colour_of_flesh+Depth_of_eyes+Smoothness_of_skin+Colour_of_base_of_lightsprout+Maturity+Height_of_plants+Frequency_of_berries+(1|Product_ID), data = potato)
summary(res1)
logLikelihood = logLik(res1)
deviance = -2*logLikelihood[1]; deviance
p = 12 # number of parameters = 3 (fixed) + 1 (random)
deviance + 2*(p+1)
coef(res1)
install.packages("lmerTest")
library(lmerTest)
res2 = lmer(Price ~ Country+Shape_of_tuber+Colour_of_skin+Colour_of_flesh+Depth_of_eyes+Smoothness_of_skin+Colour_of_base_of_lightsprout+Maturity+Height_of_plants+Frequency_of_berries+(1|Product_ID), REML = TRUE,data = potato)
summary(res2)
potato_new=potato[!(potato$Product_ID==227 & potato$Product_ID==11 & potato$Product_ID==236),]
res3 = lmer(Price ~ Country+Shape_of_tuber+Colour_of_skin+Colour_of_flesh+Depth_of_eyes+Smoothness_of_skin+Colour_of_base_of_lightsprout+Maturity+Height_of_plants+Frequency_of_berries+(1|Product_ID), REML = TRUE,data = potato_new)
summary(res3)
